#!/usr/bin/env python3

import sys
import csv
import pprint
import json


def usage():
    print("Usage:\n\t", sys.argv[0], '"Atelier Sophie 2 - Item Effects.csv"')


items = {}
edges = {}

if __name__ == "__main__":
    if len(sys.argv) != 2:
        usage()
        sys.exit(1)

    file_name = sys.argv[1]
    with open(file_name, newline="") as csvfile:
        spamreader = csv.reader(csvfile)
        for row in [r for r in spamreader if r[1] != ""][1:]:
            item = row[1]
            ingredient = row[5]
            items[item] = {"id": item}
            items[ingredient] = {"id": ingredient}
            edge_id = "edge__" + row[1] + "__" + row[5]
            edges[edge_id] = {"id": edge_id, "from": row[1], "to": row[5]}

    print(
        "// Generated by "
        + sys.argv[0]
        + "\n// DO NOT EDIT BY HAND!\nlet data=`"
        + json.dumps({"items": items, "edges": edges})
        + "`"
    )
