name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1

      - uses: actions/setup-node@v3.1.1

      - name: Init deps
        run: pnpm --frozen-lockfile

      - name: Build
        run: pnpm build
